import {ToastContainer} from "react-toastify";
import ReactQueryProvider from "@/app/providers/ReactQueryProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
    <ReactQueryProvider>
      {children}
      <ToastContainer />
    </ReactQueryProvider>
      </body>
    </html>
  )
}
